backend:
  name: git-gateway
  branch: master

media_folder: static/content/img
public_folder: /img

site_url: https://powerdev.netlify.com
logo_url: https://powerdev.netlify.com/content/img/ghost-logo.png

publish_mode: editorial_workflow

collections:

  - name: "site"
    label: "Site"
    files:
      - label: "Branding"
        name: "branding"
        file: "static/content/site/branding.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Url, name: url, widget: string }
          - { label: "Logo", name: "logo", widget: "custompathimage", customMediaPath: "../img/", rawMediaPath: "https://raw.githubusercontent.com/clarkeadg/power-dev-blog/master/static/content/img/" }

      - label: "Nav"
        name: "nav"
        file: "static/content/site/nav.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Url, name: url, widget: string }

  - name: "pages"
    label: "Page"
    folder: "static/content/pages"
    create: true
    slug: "{{slug}}"
    preview_path: pages/{{slug}}
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Author", name: "author", widget: "hidden", default: "Ghost" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "custompathimage", customMediaPath: "../img/", rawMediaPath: "https://raw.githubusercontent.com/clarkeadg/power-dev-blog/master/static/content/img/" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Post"
    folder: "static/content/posts"
    create: true
    slug: "{{slug}}"
    preview_path: posts/{{slug}}
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Author", name: "author", widget: "hidden", default: "Ghost" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "custompathimage", customMediaPath: "../img/", rawMediaPath: "https://raw.githubusercontent.com/clarkeadg/power-dev-blog/master/static/content/img/" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }



